### ISSUE TITLE
volcano plots legend has duplicate entries

### ISSUE THREAD

**Issue by sreichl** [epigen/dea_limma#4]
config.yaml

```yaml
volcano:
    pCutoff: 0.05
    FCcutoff: 0
```

<img width="317" alt="Screen Shot 2023-04-29 at 14 12 43" src="https://user-images.githubusercontent.com/53785552/235301951-aa3832b4-1be3-41a2-b92e-b876796f5a22.png">
